site_name: FuseML Documentation
nav:
    - Home: index.md
    - About: about.md
    - Quick Start: quickstart.md
    - Tutorials:
        - Logistic Regression with MLFlow & KFServing: tutorials/kfserving-basic.md
        - Training & Serving ML Models on GPU with NVIDIA Triton: tutorials/kfserving-triton-gpu.md
    - Architecture: architecture.md
    - API Reference: api.md
    - CLI Reference: cli.md
    - Contributing: CONTRIBUTING.md
theme:
  name: material
  palette:
    primary: green
    accent: cyan
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

repo_url: https://github.com/fuseml/fuseml
edit_uri: https://github.com/fuseml/docs/edit/main/docs/

plugins:
  - render_swagger


markdown_extensions:
  # Allows rendering images using HTML (see: https://squidfunk.github.io/mkdocs-material/reference/images/)
  - md_in_html
  - attr_list
  # Allows code blocks under lists (see: https://github.com/mkdocs/mkdocs/issues/282)
  - pymdownx.superfences:
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format

# TODO: Validate with our legal team.
copyright: "Copyright &copy; 2021 FuseML Author(s)"

extra:
  version:
    provider: mike